version: '3'

services:
  app:
    image: sprachenrad:latest
    ports:
      - "8080:8080" # Map the container's port 8080 to host port 8080
    depends_on:
      - mysql
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sprachenrad
    volumes:
      - ./data/db:/var/lib/postgresql/data