version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sprachenrad:latest
    ports:
      - "8080:8080" # Map the container's port 8080 to host port 8080
    depends_on:
      - db
    volumes:
      - ./data/db:/app/data/db   # Update the volume mapping
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sprachenrad_db
      POSTGRES_USER: sprad_user
      POSTGRES_PASSWORD: sprad_pw
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data

volumes:
  postgres-data: