version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sprachenrad:latest
    ports:
      - "8080:8080" # Map the container's port 8080 to host port 8080
    depends_on:
      - db
    volumes:
      - ./data/db:/app/data/db   # Update the volume mapping

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sprachenrad_db
      POSTGRES_USER: sprad_user
      POSTGRES_PASSWORD: sprad_pw
    ports:
      - "5432:5432"
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d  # Mount the initialization scripts
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres-data:
  pgadmin: